# docker-compose.yml

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    BRONZE_BACKEND: "minio"
    BRONZE_BUCKET: "bronze-layer"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./src/spark:/opt/spark-apps
    - ./scripts:/opt/airflow/scripts
    - ./config:/opt/airflow/config
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Data \
          --lastname Engineer \
          --role Admin \
          --email admin@example.com

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000" # Port API (S3)
      - "9001:9001" # Port Interface graphic
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-volume:/data
    restart: always

  spark:
    image: bitnamilegacy/spark:latest
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      - SPARK_MODE=master
      - HOME=/tmp
    ports:
      - "7077:7077" # Port for Spark master
      - "8081:8080" # Port for Spark Web UI
    volumes:
      - ./data:/opt/airflow/data
      - ./src/spark:/opt/spark-apps
    restart: always

  spark-worker:
    image: bitnamilegacy/spark:latest
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - HOME=/tmp
    depends_on:
      - spark
    volumes:
      - ./data:/opt/airflow/data
      - ./src/spark:/opt/spark-apps
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      SILVER_BUCKET: "silver-layer"
    volumes:
      - ./data:/app/data
    depends_on:
      - minio
    restart: unless-stopped

volumes:
  postgres-db-volume:
  minio-volume: